### ISSUE TITLE
Impossible to get object for element if it's inside an iframe

### ISSUE THREAD

**Issue by d-konovalov** [cheezy/page-object#224]
Hi, @cheezy, I've trapped into the issue described [here](http://www.cheezyworld.com/2011/07/29/introducing-page-object-gem/#comment-6500). 

I need to have access to generated methods available for TableRow objects, and the only way is to get them using 'each' (or some other) for Table object. 
Table object is available after using some_name_element like method. And my table is inside iframe, so I'm getting the error: 'Element belongs to a different frame than the current one – switch to its containing frame to use it'

**Comment by yudi2312** [comment]
any update on this ?

**Comment by hoguej** [comment]
Any update? 

----O--(_)---O---

**Comment by swc001** [comment]
I was able to get around it in Selenium by first assigning the element object to a local variable and then using 'switch_to' to get around the framing problem. This could possibly be fixed by overriding the find_element method for Selenium...? I haven't tried that yet.

ele = page.name_element
browser.switch_to.frame('your-frame-name')
puts ele.text  # or whatever method for the element that is needed
browser.switch_to.default_content

You must switch back to default_content. If you write helper routines, you may need to have rescue and possibly ensure blocks to do the switch back to default_content, else the next find_element will fail.

**Comment by AlexisKAndersen** [comment]
This issue is fixed with the recent page-object changes. If anyone experiences these issues with the newest version of page object, feel free to reopen.
