### ISSUE TITLE
equals operator for element mishandles nil

### ISSUE THREAD

**Issue by sciros** [cheezy/page-object#244]
Classes with issues:
<pre>page-object\platforms\selenium_webdriver\element.rb
page-object\platforms\watir_webdriver\element.rb</pre>

They both have an override for ==(other) as follows:

<pre>def ==(other)
  element == other.element
end</pre>

The problem is a test such as
<pre>expect(my_div != nil).to be true</pre>
fails with a null pointer error because it tries to invoke .element on nil.

The workaround is to flip the operands and write 'nil != my_div' but that isn't ideal.

There should be logic within this method to check if other is nil, and handle that case accordingly.

**Comment by daneandersen** [comment]
This is a good point. This method will fail if other is anything that doesn't respond_to? :element

**Comment by jkotests** [comment]
Just out of curiosity, when would you want to test if a PageObject::Element is nil? I would have thought one would be checking if the element exists or is visible.

Personally, I think I would have preferred to write (which would avoid the error):

    expect(my_div).not_to be nil

**Comment by daneandersen** [comment]
The point is if you are checking if an element is the same as another
element, you have to null check it first so you don't get an error.

**Comment by jkotests** [comment]
Sorry, I understood your point about `other` not responding to `element`.

My question was on the the assumption that `expect(my_div != nil).to be true` was literally the test being run in their test suite (rather than a test to prove a bug in the page object framework). Given that `my_div` is a PageObject::Element, it would never be nil. That is why I was asking why they were doing that test.

**Comment by daneandersen** [comment]
This should be fixed in the next release.
