### ISSUE TITLE
[FEATURE] Add check whether @current_page is a class_name before overriding in on() method

### ISSUE THREAD

**Issue by d-konovalov** [cheezy/page-object#251]
Hi @cheezy, I'd like to suggest you to place additional check into the on(SomePageClass) method (in page_factory.rb file). 
I have a lot of actions and assertions on (each) one single page and I'd like to have possibility to use common class features for each Page Object (add some attributes to store there some info) and it's possible only if I use @current_page method further in my tests. And if somewhere new on(SomePageClass) method appears - the new Page Object is created and all info stored in object attributes are gone.

its implemented here
```ruby
@current_page = page_class.new(@browser, visit)
```

So I suggest you to check if @current_page is an instance already of the page class going to be created. 

If so we could not to create new instance and use @current_page. If no - we create the new page object and place it into @current_page var. 
What you think about it?

**Comment by daneandersen** [comment]
I have a number of concerns about this feature. The way things are set up now, there are three hooks that happen on page initialization, one of which is to navigate to the page if we call `visit_page`. On top of that, a page-object is supposed to represent the method of interacting with a page, so trying to use it to store data being used for testing feels like it is giving it too many responsibilities.

My suggestion would be to use a different class to hold on to important test data instead of the PageObject.

**Comment by daneandersen** [comment]
I'm closing this. Feel free to reopen if you feel there is still a need for this feature and want to discuss it.
