### ISSUE TITLE
"text is not available on button element in Selenium"

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#275]
"text is not available on button element in Selenium" is confusing because `.text` does work, page-object just makes it a runtime error. How else are you suppose to get the inner text of a link?

- https://github.com/cheezy/page-object/blob/cf3f29d9e1dbf165ee196bfbdbfccd0b2641a606/lib/page-object/platforms/selenium_webdriver/button.rb#L10

I don't think page-object should randomly be removing parts of the selenium API and creating runtime errors. Would you accept a PR to remove this feature?

**Comment by bootstraponline** [comment]
I'm using the following work around for now:

```ruby
def fix_button_text
  PageObject::Platforms::SeleniumWebDriver::Button.module_eval do
    def text
      @element.text
    end
  end
end
```

**Comment by daneandersen** [comment]
The code you referenced has a comment

```ruby
# Override PageObject::PLatforms::SeleniumElement#text because
# #text does not reliably return a value in Selenium
```

Has something changed to make this no longer the case?

**Comment by bootstraponline** [comment]
[text](https://github.com/SeleniumHQ/selenium/blob/51fd82ec9cb1ebe7596bf7bb3fb8290113466a9a/rb/lib/selenium/webdriver/common/element.rb#L125) works fine for me. The philosophy of page-object shouldn't be to randomly raise errors on core parts of the selenium API, especially when there's no alternative.

**Comment by jkotests** [comment]
I would guess that the comment is related to the fact that there are various types of buttons. For example:
````
<input type="button" id="input_button" value="input button">
<button id="button_button">button button</button>
````
The input type buttons show "text" in the button that comes from the value attribute rather than a text node. As a result, the `text` method for inputs returns an empty string. On the other hand, the button element has a text node that is returned by the `text` method.

In Watir, there is code to handle getting the visible text based on the element type. You could implement the same for Selenium Page Objects.

**Comment by daneandersen** [comment]
thanks for the input @jkotests I'll look into that.

**Comment by bootstraponline** [comment]
Because there are various types of buttons and page-object has no idea what kind we're dealing with, page-object shouldn't be redefining core selenium methods to raise an error. The user should in charge of deciding what methods to invoke because they know the website being automated better than page-object.

**Comment by daneandersen** [comment]
I understand your concerns, but as far as I can tell, the page object style has been to provide a common API regardless of what's powering it. If you wrote all of your code referencing specifically value for input based buttons, you'd never be able to change to watir-webdriver. And if you used text everywhere using watir-webdriver, when you switch to selenium-webdriver, all input based buttons would stop working correctly.

it sounds like it would be simple enough to do a switch on `tag_name` so that we provide either the text or the value. I'll look into this.

**Comment by bootstraponline** [comment]
> the page object style has been to provide a common API regardless of what's powering it

Replacing selenium methods with a raise is removing an API, not providing one.

**Comment by daneandersen** [comment]
I'm sorry @bootstraponline I think we've had a miscommunication. I'm saying that I intend to change the behavior of page-object and remove the fail statement. But instead of leaving it in the hands of the user to figure out whether they need the_button_element.text or the_button_element.value, I'm going to make the method handle it more intelligently.

**Comment by bootstraponline** [comment]
:+1:

**Comment by daneandersen** [comment]
the fix for this is merged. It should be in the next release coming up.

**Comment by bootstraponline** [comment]
Thanks. [The fix](https://github.com/cheezy/page-object/pull/279/files) looks good to me.
