### ISSUE TITLE
Find by css uses the wrong watir locator

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#285]
```ruby
> my_page.my_button_element.class
=> PageObject::Elements::Button
> my_page.my_button_element.instance_variable_get('@element')
=> #<Watir::HTMLElement:0x4e7ee1ddc70333c8 located=false selector={:css=>"some css"}>
> my_page.my_button_element.instance_variable_get('@element').class
=> Watir::HTMLElement
> my_page.my_button_element.tag_name
=> "input"
> my_page.my_button_element.value
=> "value of the input"
> my_page.my_button_element.text
=> ""
```

I expected to trigger the [button text method](https://github.com/watir/watir-webdriver/blob/master/lib/watir-webdriver/elements/button.rb#L24) that watir provides however it doesn't work because Watir::Button isn't the underlying class (instead it's the more general Watir::HTMLElement).

Is this a bug?

Edit: I'll post tomorrow with an open source example to demo the issue.

**Comment by daneandersen** [comment]
can you include a definition of `my_button`? That might add some clarity to this.

**Comment by bootstraponline** [comment]
@daneandersen Here's a [fully open source example](https://github.com/bootstraponline/watir_example) that shows a few issues:

- `home_page.sign_up_button_element` doesn't actually find the element due to lazy loading. How am I suppose to check for an elements existence? I guess I have to use the `?` method?
- The `button` method works with any html tag, including anchors
- The wrapped class for the `button` method is the generic Watir class instead of the Button class so methods like text don't work as expected

**Comment by daneandersen** [comment]
alright, I did a little digging into your example. It looks like css selectors don't check element type. I was able to replace the css selector for the header `'h1.heading'` and pulled the header element in the button. If you were to use one of the other selectors like `:id`, `:class`, `:text` etc. then it would give you a message more like: `Watir::Exception::UnknownObjectException: unable to locate element, using {:text=>"Sign up", :tag_name=>"button"}`

I'm not sure whether there's a needed resolution to this, but it seems like the requirement of checking element types is on the user when using css selectors for the time being.

**Comment by bootstraponline** [comment]
The problem is the .text method works inconsistently for buttons across selenium webdriver vs watir. Selenium doesn't have this issue due to the dynamic patch. The fix would be to use the correct watir class (watir button) instead of the superclass (watir element).

**Comment by bootstraponline** [comment]
Maybe the easy fix is to apply the selenium_button_text fix to watir also.

**Comment by daneandersen** [comment]
well the idea is that a button is not the supported way to represent a
link. If you use link_element, everything will work straight out of the box
with either webdriver.

**Comment by jkotests** [comment]
@daneandersen, I believe you are right that the page-object does not validate the element type returned by Watir/Selenium. However, I think the problem here is that when using CSS-selectors, the generated Watir call uses the generic `element` method rather than something specific - eg `button`. 

The following [lines in the Watir-Webdriver page-object](https://github.com/cheezy/page-object/blob/master/lib/page-object/platforms/watir_webdriver/page_object.rb#L473-L476) seem suspicious:

````````
def button_for(identifier)
  call = call_for_watir_element(identifier, "button(identifier)")
  find_watir_element(call, Elements::Button, identifier)
end
```````

where `call_for_watir_element` is:

```````
def call_for_watir_element(identifier, call)
  identifier[:css] ? "#{css_element}" : call
end
```````

and `css_element` is:

```````
def css_element
  "element(identifier)"
end
```````

If I am reading this correctly, then the accessor:

```````
button(:my_button, :css => 'button#id")
```````

Will eventually make the Watir call:

```````
browser.element(:css => 'button#id')
```````

This results in a Watir::HTMLElement as opposed to the expected Watir::Button which would be created by calling:

```````
browser.button(:css => 'button#id')
```````

I would guess that this special CSS locator logic is a left over of when [Watir-Webdriver only supported CSS locators when using the `element` method](https://github.com/watir/watir-webdriver/issues/124). We should be able to remove all calls to `call_for_watir_element` and `call_for_watir_elements`.

**Comment by bootstraponline** [comment]
> I think the problem here is that when using CSS-selectors, the generated Watir call uses the generic element method rather than something specific - eg button.

Right, that is the issue.

**Comment by bootstraponline** [comment]
This fixes the problem for me:

```ruby
        def call_for_watir_element(identifier, call)
          call
        end

        def call_for_watir_elements(identifier, call)
          call
        end
```

The specific selector shouldn't be replaced with the more general one.

```
[1] pry(#<PageObject::Platforms::WatirWebDriver::PageObject>)> identifier
=> {:css=>"a[href=\"/join\"]"}
[2] pry(#<PageObject::Platforms::WatirWebDriver::PageObject>)> call
=> "button(identifier)"
[3] pry(#<PageObject::Platforms::WatirWebDriver::PageObject>)> css_element
=> "element(identifier)"
```

**Comment by bootstraponline** [comment]
@jkotests Thank you for figuring out the issue. I've submitted a [pull request](https://github.com/cheezy/page-object/pull/286) that implements your suggested fix.
