### ISSUE TITLE
Test case spans 2 browsers windows - Can Page-Object be utilized?

### ISSUE THREAD

**Issue by tk8817** [cheezy/page-object#287]
**Question:** Can I have my page-objects switch reference between 2 browsers during a scenario.

**Use Case:** I have a set of test cases in which I need to make a phone call between 2 android phones. Each phone is controlled via a web interface and requires its own browser window. 

The test flows is:
1. Login to website with Account 1 (window 1)
2. Login to website with Account 2 (window 2)
3. Place a call from Account 1 ---> Account 2 (window 1)
4. Pick-up call from Account 2 (window 2)
5. Hang up call from either account (window 1 or 2)

I have been able to master a single account / single window version of this test -- the interaction itself has not been a challenge. However, I have not been able to utilize my page-objects in the second window. I have had mild success using the below work-around:

Step 1. Use cucumber tag hooks to open a 2nd browser for the tag @phone_call.

``` ruby
Before('@phone_call') do
  browser_two = RDee.watir_browser(target = :chrome, options = {})
  @browser_two = browser_two
end
```

Step 2. Control the 2nd browser with direct watir-webdriver calls to the web-interfaces elements, thus circumventing my page-objects.

**Comment by daneandersen** [comment]
The page factory included in the page-object gem assumes you have an instance variable called `@browser`, which is referenced when creating the page object:

`on(MyPage)` is equivalent to `MyPage.new(@browser)`

So you could create the second page object manually:

`MyPage.new(@browser_two)` and that page object would reference the second browser instead of the first.

**Comment by dingokiller** [comment]
Fantastic! This is exactly the knowledge I was missing. Looking forward to getting even more out of this awesome gem.

**Comment by daneandersen** [comment]
unfortunately, since the page factory methods statically reference `@browser`, the only way would be to change what `@browser` is referencing:

```ruby
@browser = browser1
on(MyPage) do |page|
  #do stuff
end

@browser = browser2
on(MyPage) do |page|
  #other stuff
end
```

unfortunately, this is a little unwieldy, and could get you into trouble since you may not know what browser will be referred to down the line. Ultimately, this is probably more effective:

```ruby
page = MyPage.new(browser1)
#do stuff
page2 = MyPage.new(browser2)
#more stuff
```

especially if not every test needs this approach.

**Comment by abdulgmohd** [comment]
I have a similar use case as mentioned in earlier post, but the difference is instead of multiple windows I am dealing with the tabs

Here is the test flow:
it "..." do
Visit HomePage ( tab1)
on(HomePage ).click_register  ( will open RegistrationPage on the 2nd tab)
on(RegistrationPage ).fill_basicinfo_and_submit 
expect(condition).to eq(expected)
end
it "..." do
Visit HomePage ( tab1)
on(HomePage ).click_register  ( will open RegistrationPage on the 2nd tab)
on(RegistrationPage ).fill_basicinfo_and_submit 
expect(condition).to eq(expected)
end

I am getting error: Selenium::WebDriver::Error::NoSuchElementError: no such element: Unable to locate element: 

Any idea on how to switch to RegistrationPage, ie on tab2 and continue the remaining flow?

Thanks in advance!

**Comment by abdulgmohd** [comment]
did some research and found a workaround
handle = @browser.window_handles.last
@browser.switch_to.window(handle)

Cheers!
