### ISSUE TITLE
Return true when click is called.

### ISSUE THREAD

**Issue by magicalbanana** [cheezy/page-object#305]
Right now when we call click it just returns nil. It would be good if the click returns true or some sort of affirmation that it was successful.

**Comment by jkotests** [comment]
What would you consider an unsuccessful click?

Unless an exception is raised, eg element does not exist or is not visible, the click would be successful. If the application does not behave as expected, that means you are either attempting to click the wrong object, there is a bug in the application or a bug in Selenium-WebDriver. For those scenarios, I do not think the page object could detect a wrong click. Instead of asserting the return value of the click method, I think you should be asserting the behaviour you expected the click to do.

**Comment by cheezy** [comment]
It is as @jkotests stated.  There is no way for us to determine if it was a "successful" click (whatever that means).  I"m going to close this issue.  Please open if you think there is something else we should do.
