### ISSUE TITLE
can we have a .if_visible method?

### ISSUE THREAD

**Issue by ufo2mstar** [cheezy/page-object#321]
:8ball: idea
Instead of doing 
_some_element.when_visible(0).click_
or
_some_element.click if some_element.visible?_

can we have a 
**some_element.if_visible.click**
Same thing.. but i thought it would be _convenient_ and would _read better_! :+1:

**Comment by daneandersen** [comment]
To chain methods like this, the if_visible method would have to return something that responded to click but didn't actually click the element. This is technically possible with null objects, but it opens up a can of worms. If someone captured the null object or attempted to chain more methods, there could be some unexpected responses.

Something less likely to cause problems would be a method that takes a block:

```ruby
some_element.if_visible do |element|
  element.click
end
```

of course that isn't really less verbose than

```ruby
if some_element.visible?
  some_element.click
end
```

but it does also allow an interesting syntax like:

```ruby
some_element.if_visible(&:click)
```

But of course, that would only work if the action to perform is a single method to call. Still, overall I have some concerns, because it doesn't make it very obvious to new users that this is a conditional action that may or may not happen.

**Comment by ufo2mstar** [comment]
Haha.. I agree.
This is just a feature suggestion which I think will be really cool to have..

I was hoping that instead of returning a `nil` object from the `if_present/if_visible` method we can define a new class called `absent` or something that overrides all actions of any other element and hence
```ruby
any_element.if_visible || any_element.if_present
```

does just a visibility check, and I was thinking we can return a new `absent` class object,
```ruby
# if visible, just pass the element to the chain
# if not visible, then it is `absent`, and we can do an `any_element.exists?` on it and print out an **element is present but not visible** kinda message..
# And if it is does not even exist! then just nullify all actions passed in the chain, which is what that `absent` class object will do..
```
PS: Because right now I am just writing my own `wait_until(0)` kinda block to do the same..
Do you think such an `absent` class is viable? 
I personally feel it will not lead to a whole lotta confusion and will make the code more human readable and avoid more explicit conditionals and weird blocks..
What say?

**Comment by jkotests** [comment]
It's an interesting idea. However, there haven't been a lot of requests for this, so we're going to close for now. If demand rises, we can look at this again.
