### ISSUE TITLE
Support for single page applications

### ISSUE THREAD

**Issue by gssjr** [cheezy/page-object#330]
It would be nice to implement a way for PageObject to automatically retry finding elements on a page (given a timeout) in case of single page applications when nearly every element is loaded with AJAX. Capybara has a similar feature implemented: http://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/Node/Base:synchronize

Edit: clarifications

**Comment by AlanLGuy** [comment]
I haven't used Capybara in several years but does  `PageObject.default_page_wait= 10` and  `wait_until {block}`  not work for your app?

Our application is a single page web app with lots of asynchronous javascript and I find that a global wait value is almost never preferable to waiting for an explicit condition(ie field to populate, wait for a specific element to appear). But in a pinch, `wait_for_ajax` also works if your app is using a common javascript framework.

**Comment by gssjr** [comment]
To clarify, I was suggesting a way to have PageObject retry finding/interacting with an element before claiming that element can't be found. So maybe, for example, find_watir_element (or whichever method it is that finds an element) could implement a wait_until_element_present(timeout=PageObject.default_timeout). What I'm not suggesting is having PageObject wait a certain amount of time before performing the find_element.

There are too many places in my application where I need to implement "x_when_ready" methods, use wait_until, or wait_for_ajax, etc...

**Comment by bootstraponline** [comment]
Isn't this exactly what the [selenium wait method](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/wait.rb) is for?

**Comment by gssjr** [comment]
I found this which may be exactly what I'm looking for:

```
require 'watir-webdriver'
b = Watir::Browser.new
b.driver.manage.timeouts.implicit_wait = 3 #3 seconds
```

from: http://watirwebdriver.com/waiting/

**Comment by bootstraponline** [comment]
http://elementalselenium.com/tips/47-waiting

Implicit waits aren't recommended.

**Comment by gssjr** [comment]
@bootstraponline This seems to be a concern when distinguishing between the visibility of an element versus whether an element exists or not. I believe Capybara's synchronize method only re-runs for ElementNotFound exceptions, but isn't used for visibility of elements. But your point still probably stands because then I'd be missing a solution for the cases when dealing with element visibility.

What would you guys suggest? Just bite the bullet and implement tons of new methods in my PageObjects with explicit waits? If anyone has a repository of an AJAX heavy / single page app that tackles this problem I'd be grateful for a link.

**Comment by bootstraponline** [comment]
In my [framework](https://github.com/bootstraponline/angular_automation) I would wait for element visibility like this:

`wait_true(timeout: 30) { element.displayed? }`

I publish the wait method in the [webdriver_utils](https://github.com/bootstraponline/webdriver_utils) gem.

I also patch the selenium driver to [automatically perform a wait](https://github.com/bootstraponline/angular_webdriver/blob/449c605d9c43972296d6f04a8f860d43813d1b36/lib/angular_webdriver/protractor/webdriver_patch.rb#L239) on every webdriver action. The timeout is configured by using `driver.set_max_wait`

**Comment by titusfortner** [comment]
Implicit waits aren't recommended, but neither is monkey patching base libraries. ;) (and if you have to monkey patch, I recommend making liberal use of #alias_method to refer to the original code when possible). Selenium implementations are going to change soon to support w3c (I'm not sure how extensively, just be careful with how much you tinker with its internals).

Many of our automation tools aren't equipped to handle dynamic interactions as well as they need to be, and we as a community are going to need to put some more thought into how to better address these things (there aren't easy fixes). As for this issue specifically, I strongly believe that the correct place to address it is in the Watir project, (not selenium or page object libraries), and I do have plans to adjust how Watir handles waiting by default soon. Too many things going on this summer so far. :)

In the meantime, Page Object gem supports #when_present decorator, and I make liberal use of Watir's #wait_until_present as well.

**Comment by bootstraponline** [comment]
> neither is monkey patching base libraries.

There's no other way to add protractor support. It'd be nice if there was a formal plugin API to avoid the monkey patching.

**Comment by titusfortner** [comment]
I get it, I'm just saying monkey patching is rarely something that should be suggested/encouraged. If it isn't something that deserves a pull request in the main library, there's a good chance you are making the changes in the wrong place. (I haven't looked through your library enough to understand its structure).

If you feel you have to monkey patch, consider wrapping instead of replacing:
https://gist.github.com/titusfortner/92c2eba8cd6a496c62cf

Then if the underlying implementation changes, so long as the method name doesn't change you don't screw give yourself more grief. :)

**Comment by bootstraponline** [comment]
I'll see if there might be some patches I can send upstream. I agree with your point about `find_element_by`. Would watir be open to adding extension methods so adding new locators doesn't require monkey patching?

**Comment by titusfortner** [comment]
Interesting, so you are finding protractor elements by javascript instead of webdriver calls? Honestly, I'm not sure the best way to add some of this functionality and will investigate it more. Since The Honest Company's upcoming site is Angular heavy, I do have a vested interest in making these things work better as well. :)

**Comment by bootstraponline** [comment]
> Interesting, so you are finding protractor elements by javascript instead of webdriver calls?

Right. It's [all JavaScript](https://github.com/bootstraponline/angular_webdriver/blob/273cb1d4dec0037b7f655811b0c1d6e26ed002eb/lib/angular_webdriver/protractor/client_side_scripts.rb) that's dynamically generated using node to process the protractor repo as a submodule. I'm doing angular testing with page-object/watir-webdriver for my day job so any improvements in this area are welcome.

I also ported a bunch of the protractor [upstream tests](https://github.com/bootstraponline/angular_webdriver/tree/273cb1d4dec0037b7f655811b0c1d6e26ed002eb/spec/upstream/basic) and am using their [testapp](https://github.com/angular/protractor/tree/master/testapp) to validate the Ruby bindings are working correctly.

**Comment by titusfortner** [comment]
All these things after the Selenium Conference. :)

**Comment by bootstraponline** [comment]
There's a talk at Selenium Conference about angular & selenium. Might be interesting.

> `An Angular JS Testing Framework for the Rest of Us: Porting Protractor to Python`

**Comment by vveliev** [comment]
I'm new to this and I have run in to the similar problem, problem with using just wait_until is that when you select element it may be in the stage of preparing data , and validation will pass. But data is old in the page. And sometimes I run in the situation when I try to select result element when data being updated. And I get "Element is no longer attached to the DOM" error, and as a solution I use retry.  I don't like this solution but it does the job .... 

```ruby
  def page_results
    ret_count = 0
    begin
      wait_until(30, 'Page results are not available') do
        result_data_div? ? result_data_div_element.visible? : false
      end
      return result_data_div_element.div_elements(class: 'listResult-data-row').size
    rescue
      sleep 1
      (ret_count += 1) < 6 ? retry : (raise  $!)
    end
  end
```

**Comment by vveliev** [comment]
How about using:
```
 wait_for_ajax(timeout = 30, message = nil)
```
before looking for an element ?

**Comment by snowe2010** [comment]
I've noticed that `wait_for_ajax` hardly ever works for GWT based SPAs. So it isn't a foolproof solution.

**Comment by cheezy** [comment]
It is JavaScript framework specific. It can be extended to support any framework.

**Comment by titusfortner** [comment]
vveliev- I made some changes in Watir earlier this year that should mostly get rid of stale element reference errors. Retries are unfortunately still often necessary, as the wait_for_ajax is not a cure all, even with the right framework. Also, when doing rescues, try to only rescue the expected error that should trigger the retry rather than all errors.

**Comment by JESii** [comment]
> Many of our automation tools aren't equipped to handle dynamic interactions as well as they need to be, and we as a community are going to need to put some more thought into how to better address these things (there aren't easy fixes).

A big +1 for that idea. I've been writing test scripts for mobile apps for a couple of years now and ensuring that an element on the page is actually ready for some action is an ongoing problem. As pointed out above, wait_for_ajax is not reliable and we are constantly jumping through hoops to make things more deterministic. One of the  ways we've found to work around this problem is to *[gasp]* have the developers set state in the code that's sent to the page: e.g., a transition "marker" that we can explicitly test to know that a transition is complete. There's got to be a better way.

**Comment by titusfortner** [comment]
I hope to have some progress on that area in Watir itself soon (I've been very focused on upcoming changes to Selenium). For now, #when_present and the new #when_enabled before actions are useful. It won't be helpful for mobile testing though. It does also require things be more deterministic. The more code that is not dependent on checking things like whether an element is or isn't present, the more reliable it will be.

**Comment by cheezy** [comment]
Jon,

Can you provide an example of when wait_for ajax is not reliable?  I haven’t seen this yet and really want to address any issues that exist.

Please note that wait_for_ajax is JavaScrip library dependent.  In other words, you need to tell it what JavaScrip library you are using.  If you are using an unsupported library then you will have to provide the additional information that is necessary in order for it to work with your library.

-Cheezy

**Comment by JESii** [comment]
It's not consistent, Cheezy, so that makes it difficult to capture a canonical example. However, I was told that some of the problems came up when other code/library in the app was asynchronously making their own ajax calls and -- if they are slow or hang -- it fouls the normal processing of the page.

**Comment by cheezy** [comment]
Jon,

When you are using your own home-grown ajax calls (instead of using AngularJS, JQuery, or something like that) then the wait_for_ajax call will not work.  Look at this directory see the implementations that are already supported - https://github.com/cheezy/page-object/tree/master/lib/page-object/javascript <https://github.com/cheezy/page-object/tree/master/lib/page-object/javascript>

In order to use one of the supported frameworks you have to tell page-object what framework you are using so it knows what JavaScript to inject into the browser.  You do this by adding this line:

PageObject.javascript_framework = :jquery

for example.

-Cheezy

**Comment by titusfortner** [comment]
I'm not a javascript person, so I can only go off of what I've seen. In my experience, an empty jquery queue doesn't necessarily mean there isn't more javascript happening. It improves things sometimes, but not always, and not consistently. I have also tried the angular code in this project and it did not seem to do anything for my site, though I didn't spend any time figuring out why not. It's on my list to take a look at [what Ed did with Python](https://confengine.com/selenium-conf-2015/proposal/1356/an-angularjs-testing-framework-for-the-rest-of-us-porting-protractor-to-python), but who knows when/if I'll get around to that. :)

**Comment by cheezy** [comment]
The method doesn’t look to see if there is javascript happening.  It counts the number of ajax requests taking place and waits until that number drops to zero.  If you are waiting for something other than ajax calls then perhaps you should use a different method.  Here is an example of the code that is executed for checking for an AngularJS ajax call:

return angular.element(document.body).injector().get(\'$http\').pendingRequests.length;

Again, when you call wait_for_ajax it will inject this javascript code into the browser and execute it until the javascript returns zero or until a timeout is reached.

**Comment by vveliev** [comment]
I will add my "10 cent"  as i believe that ``wait_for_ajax`` is reliable but it takes some time to figure out how to use it. We are using a non supported javascript framework(mootools), and solution was that our UI developer have added Project.active() option that will start counting open connections. And openHTTPs - will return number of open connections.

On the side note, I have requested to add functionality "to see number of open connection" to the core of the MooTools and failed to convince developers. Reason "functionality needed to be there to have more reliable tests" did not worked out. As if you want to have this ability you can add it yourself and then only activate when testing.

**Comment by JESii** [comment]
@cheezy... 

Our app is very large and includes a number of 3rd-party solutions (e.g., Foreses) which have their own Javascript libraries and frameworks. Thus, specifying the framework that **we** use doesn't cover all the possibilities. So that's not really your problem, but it does mean that wait_for_ajax is problematic in our situation.

**Comment by vveliev** [comment]
@JESii   - what you approach with different environment for testing where for one particular example will cover only one framework, or add logic where based on the url it will make a selection of framework.

we have different framework based on the product, but since each product have it's own configuration there is no problem with that.

**Comment by cheezy** [comment]
Is there anything actionable in this issue or should it be closed?

**Comment by bootstraponline** [comment]
I think it should be closed.

**Comment by RubyGemTSL** [comment]
@cheezy is it possible to define >1 js framework? For example the app I am testing uses jquery and angular. How would I use the wait_for_ajax method in this case?

**Comment by AlexisKAndersen** [comment]
Is have to look at the code, but my recollection is that isn't currently
possible. That said, I think it might be easy enough to set it up to take
multiple frameworks and wait for all of them. But, again, I'd have to
review the code to know for sure.

**Comment by titusfortner** [comment]
Ok, I totally went down a rabbit hole on this one, but I've just released a new version of [Watir Angular](https://github.com/titusfortner/watir_angular/) that uses the [current protractor waiting script](https://github.com/angular/protractor/blob/a62efc6e401bc1aa7408e3008ccdaa219b528636/lib/clientsidescripts.js#L124-L226).

@cheezy - protractor is using over 100 lines of code, and does not use the `getPendingHttpRequests` command, and it also supports both Angular 1 & 2, so I'm not sure if we want to update the code in page-object.

In the meantime `watir_angular` is not incompatible with `page-object`, and it can be called as desired: `WatirAngular.wait_for_angular(browser)`, or have it run after every potential DOM changing event (navigations, clicks, etc) by having it added to Watir's AfterHook, which is done with: `WatirAngular.inject_angular_wait(browser)`
