### ISSUE TITLE
Calling Helper Modules Available to all Page-objects 

### ISSUE THREAD

**Issue by tk8817** [cheezy/page-object#344]
Hey Folks,

I am automating a website which has a search bar present on every page. I have followed conventions and made a module which describes it functions and subsequently included this module on all of my page-objects. 

As the toolbar can be used from any page in real life, we want to emulate this functionality in our automation. So we call its methods with @current_page rather than a visit/on. 

```ruby
When(/^I search for {(.*)}$/) do | product |
  @current_page.search(product)
end
```
This works great, except for one massive caveat. @current_page gets reset at the end of each scenario and thus you can only call the toolbars methods if you have visited at least one page during the scenario. Trying to call a method before a visit will result in Nil returned for @current_page.

So my question is this, why is @current_page reset at the end of a scenario? Is it because the Cucumber World resets everything? What can I do to achieve the functionality I want? I do not close the browser between tests and thus after my first test, I am always on a page and want to always be able to query what my current page is. 

Any help greatly appreciated.

**Comment by tk8817** [comment]
Ok, I have found a way to accomplish what I want -- but it just raises more questions!! If I call the method using on(Page) then I am able to invoke the toolbar without visiting a page in each scenario. 

```ruby
When(/^I search for {(.*)}$/) do | product |
  on(Home).search(product)
end
```

However, this seems sketchy. Ruby is going to load my module from the Home page-object regardless of what page I am actually on. As such I would no longer need to require + include it on my other page objects. I could leave them in, but they will never get used --- if I take them out, then it is no longer clear you can access the toolbar from those page-objects.

Aaaaaahhhhhh, why is this so silly. Tell me there is a better way!

**Comment by AlanLGuy** [comment]
you are correct that @current_page is being reset because of the way Cucumber::World cleans up instance variables between scenarios. But they do this for a reason. 

Scenarios should be completely independent of each other, it shouldn't rely on any other scenario running before it. In other words it shouldn't rely on any particular page already being open. If your tests do, a single failure will cascade into multiple failures that don't really mean anything.

All that on(PageClass) does is create and instance of the specified page class. There's no magic that says it only works when you on a specific web page. So of course, as long as there is an element that matches the identifier it doesn't matter if you call on(HomePage), on(FavoritePage) or on(WhateverICallMyPage). Programmatically they do the same thing. So it really has no impact on how "emulating" what a user would do in the test.

I agree with you that calling on(Home) when you aren't actually on the home page is misleading in your test, but an instance variable that you can't be certain of the state of isn't that much better...

If you wanted to get around it, you could probably do so using a cucumber Before and After hook or an Around that stores off the value of @current_page at the end of a scenario(as something other than an instance variable in World, obviously) and then reset it before the execution of the next scenario. I personally don't like that approach very much though

**Comment by tk8817** [comment]
Hey @AlanLGuy , I appreciate the feedback and I think the on(Home) solution is best for now.

However, I want to emphasis an important point. These functions do not belong to a specific page, they belong to all pages because the toolbar is always visible. If I want to use these functions as the first part of my next scenario, cucumber/page-object are forcing me to first visit a page or make a call to a specific page to use them. 

Imagine this scenario on facebook which has a persistent search bar at the top.

Scenario 1: 
When I login to facebook
Then I should not see any errors 

Scenario 2:
When I search for 'John'
Then I should see a result

Scenario 2 is going to fail unless you first visit a page (setting @current_page again), or pass an on(Page) call. 

Would you consider this bad form / mixing scenarios? In the real world you would not want to login to facebook at the beginning of each test, you would trust the result of your prior test and move forward. 

I get the cucumber goal of having full independence but there are good reasons to abandon that goal when testing real web products. Time is money!

**Comment by titusfortner** [comment]
Improve time by running atomic tests in parallel, not by conflating your tests. It is a Bad Idea™ to make assumptions about the state your site is in at the beginning of a test. You should be able to run any test in isolation and in any order and know exactly what is broken by which test failed, not from spending a bunch of time walking through your test code to figure out where it broke and if it is a real issue or just a fluke. The costs of maintaining poorly devised tests become much more expensive in short order than how long it takes to run the tests. :)

I tend to specify the page I'm on with a Given. 'Given I am on Page Foo' ==> @current_page = visit(Foo)

As for something like being logged in, you can do that in a Before Hook or a Background statement, but then you'd have to create a separate context for actually testing the log-in.

**Comment by tk8817** [comment]
In an effort to get back on topic, let me eliminate the discussion of interference between scenarios

```ruby
Scenario 1: 
When I login to facebook
Then I should not see any errors

Scenario 2:
Given I am logged in
When I search for 'John'
Then I should see a result
```

Now we have no assumptions  and both scenarios can be run independently. However, my original issue still remains, which is that the second scenario needs to initialize another page-object to be able to execute the code I want. 

In case there are new folks just joining us, the step: When I search for 'John' is implied to map back to a helper module which drives a panel that is present on all pages. 

```ruby
When(/^I search for {(.*)}$/) do | person |
  @current_page.search(person)
end
```

**Comment by callahat** [comment]
You can always check the class of @current_page. If it's NilClass, you know you aren't logged in, and can handle that from within the step definition or a helper. Either way, relying on one test to setup the state for another test is not a good thing.

**Comment by tk8817** [comment]
@callahat , @current_page is reset between scenarios, so checking it will always return null -- this is the exact issue my thread is trying to address. It is part of the design of cucumber to reset all class variables between scenarios, so not a page-object gem issue. 

To address the larger audience in this thread, I feel like many of the folks who say 'relying on a prior test is bad' have not really thought about the value of linked tests.In real life users do not start with a fresh slate for every action they do. We use Cucumber to do real dirty E2E testing of complex user stories. 

In fact, by having links you can get quicker 'fail-fast' feedback, with less cycles wasted on steps which are known to fail. 

Example, 
lets says you need to login to do your tests, an action which based on having 0 interlinks - you would want to do in every scenario

``` ruby

Scenario: 1
Given I login
When I do A
Then I should see B

Scenario: 2
Given I login
When I do C
Then I should see D

Scenario: 3
Given I login
When I do E
Then I should see F
```

If login is failing, your test suite is going to try that failing action 3 times and if it failed once it likely had a good reason and is going to fail 2 more times. Agreed, you will know in all 3 cases that it was because of login that the test failed, and that is valuable. However, let me show you how you can get the same feedback but much faster

``` ruby
Scenario: 1
Given I login
When I do A
Then I should see B

Scenario: 2
Given I am logged in
When I do C
Then I should see D

Scenario: 3
Given I am logged in
When I do E
Then I should see F
```
With interlinked scenarios if the login fails in scenario 1, your givens will block you from entering scenarios 2 & 3. The login action is only attempted once, instead of 3 times. As the given is just a on-page check, it will execute much much faster. We get the same level of feedback for why the test failed, but we get it much faster. Moreover, it executes much more in line with how a real user would use the product! 

Having links can be a good thing and it can get you much closer to how the real world works!

**Comment by callahat** [comment]
What happens if scenario 2 breaks in such way that causes scenario 3 to fail? Have you considered using a different tool such as rspec? While this looks like its more of an issue that should be brought up in the cucumber project, Cucumber is still a collaboration tool before its a testing tool.

As much as I probably shouldn't suggest it, if you still insist on using cucumber in this way you might as well stick @browser and @current_page in globals at the end of each scenario in the feature. Not something I would want to do though.

**Comment by titusfortner** [comment]
Scenarios are designed to be independent. If you are going to treat the entire feature file as one long scenario, why not just write it that way?

**Comment by tk8817** [comment]
1. We get more detailed results / reports by breaking it down. If you make it one big scenario then you are going to either have 1 pass or 1 fail. 

2. It means we do not need to do multiple given/when/then cycles within a scenario. By breaking things down, we assert, we do, and we check once per scenario. 

3. We get clean easy to read feature files which clearly lay out what is being asserted/done/expected. 


Let me get back to your question posed before: 
'What If scenario 2 breaks in such a way that causes scenario 3 to fail' 

This is a really interesting question to examine. Lets break it down and see what happens in both cases using an example where you have scenarios which do a set of identical actions to get to a fork where you branch off. 


``` ruby
Feature 1: No Links

Scenario: 1
Given I login
When I do A
Then I should see B
When I do C  (action is dirty and causes break)
Then I should see D (fails because C was not as expected)
When I do E
Then I should see F

Scenario: 2
Given I login
When I do A
Then I should see B
When I do C  (action is dirty and causes break)
Then I should see D (fails because C was not as expected)
When I do G
Then I should see H

Scenario: 3
Given I login
When I do A
Then I should see B
When I do C  (action is dirty and causes break)
Then I should see D (fails because C was not as expected)
When I do I
Then I should see J

```

So we have 3 scenarios with the same starting steps and branch for the last action and check. 
We will see our test suite do actions login, A, B, C, and D - 3 times over and fail before getting to the interesting parts afterwards.
This is good, and we know our failures are because action C is not generating the expected result D. 
However, it is very slow to get to this state 3 times over and we are wasting cycles doing the same actions which are known to fail

``` ruby
Feature 2: Links

Scenario: 1
Given I login
When I do A
Then I should see B
When I do C  (assume this action is dirty and causes break)
Then I should see D (fails because C was not as expected)

Scenario: 2
Given D (will fail based on outcome of S1)
When I do G
Then I should see H

Scenario: 3
Given D (will fail based on outcome of S1)
When I do I
Then I should see J
```

So we have your cascading failure here. Because C did not result in D, scenario 2 & 3 will be affected. 
However, once again we have the exact same level of detail that Feature 1 gave us, we know that we cannot proceed because C did not generate the expected result D. 

Consider the benefits:
1. We got here a LOT faster, we only performed the failing actions ONCE, not * # of scenario times.
2. We have the same detailed reason for why the scenario failed
3. We more closely emulated what the user would do 
4. Our feature reads more closely to the true user story (users don't start from the beginning every time). 

I would urge you to consider just how much of a speed boost we are talking about. I am not sure what or where you are testing, but I test on production against a large user driven web-app, so on a good day our scenarios average 45 seconds each if you do the full E2E (login, setup acct, setup CC, etc). By linking actions we can take 10 x 45 sec scenarios (450sec = 7.5min) and turn that into 1.5min. A 500x performance increase. When you have 1000 cases, that is 12.5 hours vs 2.5 hours, were talking about taking 10 HOURS off of our test cycle time. 

Really take a step back and think about the risk versus reward, especially when you are designing using this method on purpose.

There is a big difference between people unknowingly and mistakenly creating links/dependancies, and designing specifically to take advantage of them while ensuring the risks are minimized (using Givens as blocks into scenarios).

**Comment by tk8817** [comment]
For clarity, my team is operations using cucumber/webdriver to test deployment success & nightly monitoring in pre-prod & prod. We are not using it as part of development (aside from testing that master is not broken at the end of the day) -- perhaps this will influence your position.

**Comment by titusfortner** [comment]
You can quickly code some highly efficient things with global variables everywhere. You can knock out an impressive suite of tests in a week using a Record and Playback tool. Those obviously aren't best practices, though. :)

There is a reason cucumber was designed with the idea that scenarios be independent; it wasn't an accident, and it wasn't because the designers didn't think about the points you made above or because they wanted your tests to run more slowly. You might be able to figure out workarounds, but every time you hack a tool to do something it was specifically designed not to do, you are making your code base less maintainable. Maybe in the context of your specific situation the potential downsides will never be an issue. Maybe you have a small team and you aren't expecting to significantly grow your test suite. Maybe you don't have to worry about what your tests are going to look like 5 years from now, or what the people who end up inheriting this code have to figure out in order to keep it up. Most people starting a project don't appreciate the full extent of the costs of code maintainability down the road. These are things you figure out when you inherit tens of thousands of tests that if they ran concurrently would take hundreds or thousands of hours to execute. The more you follow best practices and don't overcomplicate things, the less it costs you in the long run.

I just urge you to be cautious about patronizing people who have been doing this longer than you have and suggest that they aren't prioritizing the right things; and definitely don't be surprised if developers don't have ready answers for how to make their code work in a way that defeats the design goals of the tool. :)

**Comment by tk8817** [comment]
@titusfortner I was really sincere in my responses and took the time to write out both sides of the discussion in detail via through experiments. You speak heavily in your response about code quality and maintainability, but the ordering of cucumber steps has no impact on the code, you can do what I posed in Feature 1 and Feature 2 with the exact same code backing it. 

Are we truly saying that there is no responsible way to do this? If we can show a tool is able to be powerful in ways it was not initially conceived, is that a workaround? I mean, at birth Cucumber was about BDD but it is now used in many other realms.  

Think about Aruba (Cucumber for CLI) and how it is used by teams who write MOPs for deployment. Aruba steps are very commonly written in a linear fashion in which one scenario sets up the next. Cucumber allows the MOP to be a 'living document' where each step has a Given/When/Then and that is a massive benefit for teams because you get checkpoints along the way. 

Despite my best attempts to start an engaged discussion, I am only getting responses which say 'all linking is bad' or in your last post - odd points about global variables & recording software. I am not posing workarounds or shortcuts, I am trying hard to gain feedback on responsible ways to utilize dependency for massive speed gains and reduction in rerunning steps which are known to fail.

I appreciate any constructive feedback and discussion on the matter. I am not looking to offend and I can assure you that the reason I posted here in the first place is that I value the views of the community. 

In closing, we use cucumber in a operations environment, not a development environment. We care foremost about the end user and how they use the site and cucumber lets us express that in a beautiful way.

**Comment by tk8817** [comment]
to put a dead horse to rest, I am taking the risk and storing @current_page in my After step and recycling it into my Before step
