### ISSUE TITLE
radio_button, label assessor not working as expected. 

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#418]
I'm not sure if it belongs to page object or watir. 

**Selenium 3.2.0
**Chrome 56 (2.27)
**page-object 2.1.1

definition
```rb
radio_button(:forward, label: 'forwarding')
```

example html
```html
<div class="flat-radio grid-col-6">
<input type="radio" id="forwarding" name="forward-type" value="forwarding" aria-hidden="true">
<label for="forwarding" class="forwarding no-cap">
</label></div>
```

```rb
(byebug) current_page.select_forward
This code has slept for the duration of the default timeout waiting for an Element to exist. If the test is still passing, consider using Element#exists? instead of rescuing UnknownObjectException
*** Watir::Exception::UnknownObjectException Exception: timed out after 30 seconds, waiting for #<Watir::Radio: located: false; {:class=>"forward"} --> {:label=>"forwarding", :tag_name=>"input", :type=>"radio"}> to be located
```

Thank you.

**Comment by titusfortner** [comment]
Watir now waits for elements to be visible before attempting to interact with them. `aria-hidden="true"` means that the element is not displayed. Selenium should have always prevented that from being clicked. I've seen a few issues like this raised, and I haven't figured out under what conditions Selenium allows clicks on non-visible elements.

**Comment by titusfortner** [comment]
Oh, looking at the error, it isn't even finding the value in the first place.
What is the `current_page.select_forward` looking for?
If you put this before the code in question you can see what is actually getting sent to the driver and see if it matches the html:
`Selenium::WebDriver.logger.level = :info`

**Comment by vveliev** [comment]
Ok so the Idea from what i understand: 

Checkbox css styles works by using label , therefor checkbox is not visible element, but label of the same parent is visible and in order to interact with checkbox you define checkbox using label.

hmmm.... I just figure out how it works and i don't think i like it ....
```rb
radio_button(:forward, label: '#text of the label')
```

```rb
(byebug) current_page.radio_button_element(label: 'label text').select
This code has slept for the duration of the default timeout waiting for an Element to be present. If the test is still passing, consider using Element#exists? instead of rescuing UnknownObjectException
*** Watir::Exception::UnknownObjectException Exception: element located, but timed out after 30 seconds, waiting for true condition on #<Watir::Radio: located: true; {:class=>"forward"} --> {:label=>"label text", :tag_name=>"input", :type=>"radio"}>

```

So in order for label element have matching radio box , it must have an :id , and that's what i don't like .... why not use 'for'/:id attribute to select label/radio_button pair ... 

So this will not work as i don't know text of the label before hand , and I cannot use label_element as it's not defined at initialization time.

**Comment by jkotests** [comment]
The `:label` locator is meant to check the associated label element's text. The behaviour is [defined in Watir](https://github.com/watir/watir/blob/512f8487ec6a5b42465688f9c8336b3c42ab1ec2/lib/watir/locators/element/locator.rb#L188-L195).

Maybe I am misunderstanding the problem, but why wouldn't you use the `id`/`for` attribute pair?

~~~~~~~~
radio_button(:forward, id: 'forwarding')
~~~~~~~~

However, given you have said the radio button is hidden and the label is visible, the `radio_button` accessor will never work for you. Watir will always prevent clicking the radio button as it is hidden.

What you need is a widget that acts like a `RadioButton` except clicks the associated label element rather than the input element. The following is the start of such a widget:

~~~~~~~~
class HiddenRadioButton < PageObject::Elements::RadioButton
  def self.accessor_methods(accessor, name)
    accessor.send(:define_method, "#{name}_selected?") do
      self.send("#{name}_element").selected?
    end
    
    accessor.send(:define_method, "select_#{name}") do
      self.send("#{name}_element").select
    end
  end
    
  def select
    label_element.click unless selected?
  end
  
  def label_element
    element.browser.label(for: element.id)
  end   
end
PageObject.register_widget :hidden_radio_button, HiddenRadioButton, :radio

class MyPage
  include PageObject

  hidden_radio_button(:forward, id: 'forwarding')
end
~~~~~~~~

The usage would be the same as other radio buttons:

~~~~~~~~
page = MyPage.new(browser)
page.forward_selected?
#=> false
page.select_forward
page.forward_selected?
#=> true
~~~~~~~~

While not neccessary for solving this specific problem, you would also want to override the visibility and waiting methods to use the visible label element rather than the hidden input.

**Comment by vveliev** [comment]
This solves my issue ! Thank you !.

**Comment by vveliev** [comment]
https://github.com/cheezy/page-object/wiki/Custom-page-object-elements-by-using-widgets.
