### ISSUE TITLE
select_list options method does not return what is expected.

### ISSUE THREAD

**Issue by vveliev** [cheezy/page-object#424]
When I call options on select list element , it return array of PageObject::Elements::Option
where before I believe it was a text of those elements.  What should we expect ?!

**Comment by jkotests** [comment]
I think an Array of PageObject::Elements::Option is expected for the SelectLIst#options method. The code appears to have been doing that since at least 2014.

Are you perhaps mixing it up with the `*_options` method created by the select list accessor? That method does return the text of the option elements.
