### ISSUE TITLE
custom elements (widgets) with user defined tag names

### ISSUE THREAD

**Issue by entwanderer** [cheezy/page-object#451]
I'm playing around with page-object to test an angular application.

In angular, it is common practice, to have user defined tag names, e.g.:
```<my-component></my-component>```

I wonder if i can create a widget for this.

Refering to
https://github.com/cheezy/page-object/wiki/Widgets-(registering-custom-elements-with-PageObject)

```
class MyComponent < PageObject::Elements::Element

end

PageObject.register_widget :my_component, MyComponent, :"my-component"

class MyPage
   include PageObject
   my_component  :my_comp

   def some_method
      self.my_comp.exists?
   end
end
```

```
# undefined method `my_comp' for #<Selenium::WebDriver::Chrome::Driver:0xb8bc5110 browser=:chrome> (NoMethodError)
./features/support/pages/my_page.rb:12:in `some_method'
```

Looks like, that self of my PageObject is pointing to the chrome driver?
I'm very confused about that. Can you help me?

**Comment by jkotests** [comment]
At the moment, I think the easiest way to do this is to also add the respective element method to Watir.

~~~~~~~~ruby
# Define the element in Watir
module Watir
  module Container
    def my_component(*args)
      HTMLElement.new(self, extract_selector(args).merge(tag_name: "my-component"))
    end
    def my_components(*args)
      HTMLElementCollection.new(self, extract_selector(args).merge(tag_name: "my-component"))
    end
  end
end

# Create the Page-Object widget
# Note that the third parameter to register_widget is :my_component
class MyComponent < PageObject::Elements::Element
end
PageObject.register_widget :my_component, MyComponent, :my_component

# Use accessor in the page
# Note that the method available is #my_comp_element rather than #my_comp
class MyPage
   include PageObject
   my_component :my_comp

   def some_method
      my_comp_element.exists?
   end
end
~~~~~~~~

Note that if you just have to do this a couple of times, the easier solution is to just use the general element accessor:

~~~~~~~~ruby
class MyPage
   include PageObject
   element :my_comp, tag_name: 'my-component'

   def some_method
      my_comp_element.exists?
   end
end
~~~~~~~~

**Comment by titusfortner** [comment]
Ugh this breaks html5 compliance. Oh angular. Not to mention all of the nice encapsulation provided by page object/watir. :-)

**Comment by entwanderer** [comment]
@jkotests thank you very much for your help.
I didn't know about the element accessor which seems to satisfy my needs for now.

It may be mentioned at the end of the elements description as fallback for cases like mine:
https://github.com/cheezy/page-object/wiki/Elements

@titusfortner yeah, that's right.
But HTML6(?) will come, or at least WebComponents. So support for custom tags may be considered for the future:
https://www.w3.org/standards/techs/components#w3c_all

**Comment by cheezy** [comment]
@entwanderer I'm going to go ahead and close this item since the element method seems to do what you need.  If you feel like there is the need for new behaviour please reopen.
