### ISSUE TITLE
navigate_to method calls with page_navigation's navigate_to

### ISSUE THREAD

**Issue by ynotgnef** [cheezy/page-object#485]
If we call navigate_to(url) or self.navigate_to(url) in a method defined in a pagobject, it calls the page_navigation's navigate_to (https://github.com/cheezy/page_navigation/blob/ebc2fa57592283c87fa23736017a8086f424c622/lib/page_navigation.rb#L58) instead. Is there any way to use the pageobject method in a project that also uses page_navigation?

**Comment by jkotests** [comment]
Not to familiar with Page-Navigation, but given the way the `#navigate_to` is added to the page object, you should just need to switch the order that you include them. I didn't see any obvious downstream impact in Page-Navigation.

~~~~~~~~ 
class MyPage
  include PageNavigation
  include PageObject       # must be second so that it can override PageNavigation#navigate_to
end
~~~~~~~~

Alternatively, since Page-Object's `#navigate_to` does not contain any special logic, you could just directly interact with the browser object:

~~~~~~~~
class MyPage
  def some_method_that_needs_navigation
    browser.goto(some_url)
  end
end
~~~~~~~~

**Comment by jkotests** [comment]
I am going to close this issue assuming that the above "fix" works for you. If not, please feel free to re-open.
